NAME		= myArray
	
CC			= c++
FLAGS		= -Wall -Wextra -Werror -std=c++98 -g3 
RM			= rm -rf

OBJDIR =	 .objFiles

FILES		= main 

HEADER		= Array.hpp
SRC			= $(FILES:=.cpp)
OBJ			= $(addprefix $(OBJDIR)/, $(FILES:=.o))

#Colors:
GREEN		=	\e[92;1;118m
YELLOW		=	\e[93;1;226m
RED			=	\e[33;1;31m
GRAY		=	\e[33;2;37m
RESET		=	\e[0m
CURSIVE		=	\e[33;3m

all: $(NAME)

$(NAME): $(OBJ) $(HEADER)
	@$(CC) $(OBJ) $(FLAGS) -o $(NAME)
	@printf "$(_SUCCESS) $(GREEN)- Executable ready.\n$(RESET)"

$(OBJDIR)/%.o: %.cpp $(HEADER)
	@mkdir -p $(dir $@)
	@$(CC) $(FLAGS) -c $< -o $@

clean:
	@$(RM) $(OBJDIR) $(OBJ)
	@printf "$(YELLOW)    - Object files removed.$(RESET)\n"

fclean: clean
	@$(RM) $(NAME)
	@printf "$(RED)    - Executable removed.$(RESET)\n"

re: fclean all

.PHONY: all clean fclean re bonus norm